" Personal vim configuration
" Minimal since vim bindings are primarily used in IDEs (Cursor, CLion, PyCharm)

set nocompatible
set number
set relativenumber
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
